apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery-service
        image: final-delivery-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/delivery-service"
        - name: JWT_SECRET
          value: "your_jwt_secret_key"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq"
        - name: RABBITMQ_EXCHANGE
          value: "food_delivery"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:3004/api"
        - name: USER_SERVICE_URL
          value: "http://user-service:3001/api"
        - name: RESTAURANT_SERVICE_URL
          value: "http://restaurant-service:3003/api"
        - name: AUTO_ASSIGNMENT_ENABLED
          value: "true"
        - name: MAX_DELIVERY_DISTANCE
          value: "10000"
        - name: MAX_WAIT_TIME
          value: "300"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  ports:
  - port: 3005
    targetPort: 3005
  selector:
    app: delivery-service 