apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: final-user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/food-ordering-users"
        - name: JWT_SECRET
          value: "your_jwt_secret_key"
        - name: JWT_EXPIRATION
          value: "24h"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq"
        - name: NODE_ENV
          value: "development"
        - name: FRONTEND_URL
          value: "http://localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: user-service 